--爱情加工厂
menuBtn.onClick=function()
  退出页面()
end
require "import"
import "android.app.*"
import "android.os.*"
import "android.widget.*"
import "com.lua.views.MarTextView"
  ghost={
    LinearLayout,
    layout_height="match_parent",
    layout_width="match_parent",
    orientation="vertical",
    background="#FFFFFFFF";
    {
      ScrollView,
      layout_width="match_parent";
      layout_height="match_parent";
      VerticalScrollBarEnabled=false;
      {
        LinearLayout,
        layout_height="match_parent",
        layout_width="match_parent",
        orientation="vertical",
        {
          LinearLayout,
          layout_height="200dp",
          layout_width="match_parent",
          orientation="vertical",
          layout_margin="10dp",
          {
            CardView;
            layout_margin="0.5dp",
            elevation="1.5dp";
            id="k1";
            layout_width="match_parent";
            CardBackgroundColor="#EEFFFFFF";
            layout_height="match_parent";
            radius="15dp";
            {
              PageView,
              id="pg1";
              layout_width="fill",
              layout_height="fill",
              pages={
                {
                  LinearLayout;
                  id="f1";
                  layout_height="match_parent",
                  layout_width="match_parent",
                  orientation="vertical";
                  {
                    CardView;
                    elevation="1.5dp";
                    id="k1";
                    layout_width="match_parent";
                    CardBackgroundColor="#00FFFFFF";
                    layout_height="match_parent";
                    radius="15dp";
                    {
                      ImageView;
                      layout_width="match_parent",
                      layout_height="match_parent",
                      background="drawable/1.jpg";
                    },
                    {
                      TextView,
                      layout_height="30dp",
                      layout_width="match_parent",
                      layout_gravity="bottom",
                      gravity="center",
                      background="#44000000";
                      text="",
                      textSize="15sp",
                    },
                  },
                },
                {
                  LinearLayout;
                  id="f2";
                  layout_height="match_parent",
                  layout_width="match_parent",
                  orientation="vertical";
                  {
                    CardView;
                    elevation="1.5dp";
                    id="k1";
                    layout_width="match_parent";
                    CardBackgroundColor="#00FFFFFF";
                    layout_height="match_parent";
                    radius="15dp";
                    {
                      ImageView;
                      layout_width="match_parent",
                      layout_height="match_parent",
                      background="drawable/2.jpg";
                    },
                    {
                      TextView,
                      layout_height="30dp",
                      layout_width="match_parent",
                      layout_gravity="bottom",
                      gravity="center",
                      background="#44000000";
                      text="",
                      textSize="15sp",
                    },
                  },
                },
                {
                  LinearLayout;
                  id="f3";
                  layout_height="match_parent",
                  layout_width="match_parent",
                  orientation="vertical";
                  {
                    CardView;
                    elevation="1.5dp";
                    id="k1";
                    layout_width="match_parent";
                    CardBackgroundColor="#00FFFFFF";
                    layout_height="match_parent";
                    radius="15dp";
                    {
                      ImageView;
                      layout_width="match_parent",
                      layout_height="match_parent",
                      background="drawable/3.jpg";
                    },
                    {
                      TextView,
                      layout_height="30dp",
                      layout_width="match_parent",
                      layout_gravity="bottom",
                      gravity="center",
                      background="#44000000";
                      text="",
                      textSize="15sp",
                    },
                  },
                },
              },
            },
          },
        },
        {
          LinearLayout,
          layout_height="wrap_content",
          layout_width="match_parent",
          orientation="vertical",
          layout_margin="10dp",
          {
            CardView;
            layout_margin="0.5dp",
            elevation="1.5dp";
            id="k1";
            layout_width="match_parent";
            CardBackgroundColor="#00FFFFFF";
            layout_height="match_parent";
            radius="5dp";
            {
              LinearLayout,
              layout_height="match_parent",
              layout_width="match_parent",
              orientation="horizontal",
              {
                LinearLayout,
                layout_height="wrap_content",
                layout_width="match_parent",
                orientation="vertical",
                layout_margin="10dp",
                {
                  LinearLayout,
                  layout_height="wrap_content",
                  layout_width="match_parent",
                  orientation="horizontal",
                  layout_weight="1.0",
                  {
                    LinearLayout,
                    layout_height="match_parent",
                    layout_width="wrap_content",
                    orientation="vertical",
                    layout_weight="1.0",
                    gravity="center",
                    {
                      LinearLayout,
                      layout_height="wrap_content",
                      layout_width="wrap_content",
                      layout_weight="1.0",
                      {
                        CircleImageView;
                        src="1.png";
                        layout_height="56dp";
                        layout_width="56dp";
                        onTouchListener=点击监听,
                        onClick=function()
                          进入子页面("情感语录")
                        end
                      };
                    },
                    {
                      TextView,
                      layout_height="wrap_content",
                      layout_width="wrap_content",
                      text="情感语录",
                    },
                  },
                  {
                    LinearLayout,
                    layout_height="match_parent",
                    layout_width="wrap_content",
                    orientation="vertical",
                    layout_weight="1.0",
                    gravity="center",
                    {
                      LinearLayout,
                      layout_height="wrap_content",
                      layout_width="wrap_content",
                      layout_weight="1.0",
                      {
                        CircleImageView;
                        src="2.png";
                        layout_height="56dp";
                        layout_width="56dp";
                        onTouchListener=点击监听,
                        onClick=function()
                          进入子页面("撩妹惯例")
                        end
                      };
                    },
                    {
                      TextView,
                      layout_height="wrap_content",
                      layout_width="wrap_content",
                      text="撩妹惯例",
                    },
                  },
                  {
                    LinearLayout,
                    layout_height="match_parent",
                    layout_width="wrap_content",
                    orientation="vertical",
                    layout_weight="1.0",
                    gravity="center",
                    {
                      LinearLayout,
                      layout_height="wrap_content",
                      layout_width="wrap_content",
                      layout_weight="1.0",
                      {
                        CircleImageView;
                        src="3.png";
                        layout_height="56dp";
                        layout_width="56dp";
                        onTouchListener=点击监听,
                        onClick=function()
                          进入子页面("一个图文")
                        end
                      };
                    },
                    {
                      TextView,
                      layout_height="wrap_content",
                      layout_width="wrap_content",
                      text="一个图文",
                    },
                  },
                  {
                    LinearLayout,
                    layout_height="match_parent",
                    layout_width="wrap_content",
                    orientation="vertical",
                    layout_weight="1.0",
                    gravity="center",
                    {
                      LinearLayout,
                      layout_height="wrap_content",
                      layout_width="wrap_content",
                      layout_weight="1.0",
                      {
                        CircleImageView;
                        src="4.png";
                        layout_height="56dp";
                        layout_width="56dp";
                        onTouchListener=点击监听,
                        onClick=function()
                          进入子页面("一个阅读")
                        end
                      };
                    },
                    {
                      TextView,
                      layout_height="wrap_content",
                      layout_width="wrap_content",
                      text="一个阅读",
                    },
                  },
                },
                {
                  LinearLayout,
                  layout_marginTop="2%h";
                  layout_height="wrap_content",
                  layout_width="match_parent",
                  orientation="horizontal",
                  layout_weight="1.0",
                  {
                    LinearLayout,
                    layout_height="match_parent",
                    layout_width="wrap_content",
                    orientation="vertical",
                    layout_weight="1.0",
                    gravity="center",
                    {
                      LinearLayout,
                      layout_height="wrap_content",
                      layout_width="wrap_content",
                      layout_weight="1.0",
                      {
                        CircleImageView;
                        src="5.png";
                        layout_height="56dp";
                        layout_width="56dp";
                        onTouchListener=点击监听,
                        onClick=function()
                          进入子页面("图片精选")
                        end
                      };
                    },
                    {
                      TextView,
                      layout_height="wrap_content",
                      layout_width="wrap_content",
                      text="图片精选",
                    },
                  },
                  {
                    LinearLayout,
                    layout_height="match_parent",
                    layout_width="wrap_content",
                    orientation="vertical",
                    layout_weight="1.0",
                    gravity="center",
                    {
                      LinearLayout,
                      layout_height="wrap_content",
                      layout_width="wrap_content",
                      layout_weight="1.0",
                      {
                        CircleImageView;
                        src="6.png";
                        layout_height="56dp";
                        layout_width="56dp";
                        onTouchListener=点击监听,
                        onClick=function()
                          进入子页面("专属情头")
                        end
                      };
                    },
                    {
                      TextView,
                      layout_height="wrap_content",
                      layout_width="wrap_content",
                      text="专属情头",
                    },
                  },
                  {
                    LinearLayout,
                    layout_height="match_parent",
                    layout_width="wrap_content",
                    orientation="vertical",
                    layout_weight="1.0",
                    gravity="center",
                    {
                      LinearLayout,
                      layout_height="wrap_content",
                      layout_width="wrap_content",
                      layout_weight="1.0",
                      {
                        CircleImageView;
                        src="7.png";
                        layout_height="56dp";
                        layout_width="56dp";
                        onTouchListener=点击监听,
                        onClick=function()
                          进入子页面("颜值评分")
                        end
                      };
                    },
                    {
                      TextView,
                      layout_height="wrap_content",
                      layout_width="wrap_content",
                      text="颜值评分",
                    },
                  },
                  {
                    LinearLayout,
                    layout_height="match_parent",
                    layout_width="wrap_content",
                    orientation="vertical",
                    layout_weight="1.0",
                    gravity="center",
                    {
                      LinearLayout,
                      layout_height="wrap_content",
                      layout_width="wrap_content",
                      layout_weight="1.0",
                      {
                        CircleImageView;
                        src="8.png";
                        layout_height="56dp";
                        layout_width="56dp";
                        onTouchListener=点击监听,
                        onClick=function()
                          进入子页面("生逢何时")
                        end
                      };
                    },
                    {
                      TextView,
                      layout_height="wrap_content",
                      layout_width="wrap_content",
                      text="生逢何时",
                    },
                  },
                };
              };
            };
          };
        };
        {
          LinearLayout,
          layout_height="wrap_content",
          layout_width="match_parent",
          orientation="horizontal",
          layout_marginLeft="10dp",
          layout_marginRight="10dp",
          layout_marginBottom="10dp",
          {
            CardView;
            layout_margin="0.5dp",
            elevation="1.5dp";
            id="k1";
            layout_width="match_parent";
            CardBackgroundColor="#00FFFFFF";
            layout_height="match_parent";
            radius="5dp";
            {
              LinearLayout,
              layout_height="match_parent",
              layout_width="match_parent",
              orientation="vertical",
              {
                LinearLayout,
                layout_height="70dp",
                layout_width="match_parent",
                orientation="horizontal",
                {
                  LinearLayout,
                  layout_height="8%h",
                  layout_width="50%w",
                  layout_weight="1.0",
                  layout_margin="10dp",
                  {
                    CardView;
                    layout_margin="0.5dp",
                    elevation="1.5dp";
                    layout_width="match_parent";
                    CardBackgroundColor="#00FFFFFF";
                    layout_height="match_parent";
                    radius="5dp";
                    {
                      ImageView;
                      layout_width="fill",
                      layout_height="fill",
                      scaleType="fitXY";
                      id="n1";
                      onTouchListener=点击监听,
                      onClick=function()
                        进入子页面("表白网页制作")
                      end
                    },
                    {
                      TextView,
                      layout_height="wrap_content",
                      layout_width="wrap_content",
                      text="表白网页制作",
                      --textSize="10sp",
                      layout_gravity="center",
                    },
                  },
                },
                {
                  LinearLayout,
                  layout_height="8%h",
                  layout_width="50%w",
                  layout_weight="1.0",
                  layout_margin="10dp",
                  {
                    CardView;
                    layout_margin="0.5dp",
                    elevation="1.5dp";
                    id="k1";
                    layout_width="match_parent";
                    CardBackgroundColor="#00FFFFFF";
                    layout_height="match_parent";
                    radius="5dp";
                    {
                      ImageView;
                      layout_width="fill",
                      layout_height="fill",
                      id="n2";
                      onTouchListener=点击监听,
                      onClick=function()
                        进入子页面("表白图片制作")
                      end
                    },
                    {
                      TextView,
                      layout_height="wrap_content",
                      layout_width="wrap_content",
                      text="表白图片制作",
                      --textSize="10sp",
                      layout_gravity="center",
                    },
                  },
                },
              },
              {
                LinearLayout,
                layout_height="50dp",--
                layout_width="match_parent",
                orientation="horizontal",
                {
                  LinearLayout,
                  layout_height="8%h",
                  layout_width="50%w",
                  layout_weight="1.0",
                  layout_marginLeft="10dp",
                  layout_marginRight="10dp",
                  {
                    CardView;
                    layout_margin="0.5dp",
                    elevation="1.5dp";
                    id="k1";
                    layout_width="match_parent";
                    CardBackgroundColor="#00FFFFFF";
                    layout_height="match_parent";
                    radius="5dp";
                    {
                      ImageView;
                      layout_width="fill",
                      layout_height="fill",
                      id="n3";
                      onTouchListener=点击监听,
                      onClick=function()
                        弹出消息("待开发")
                      end
                    },
                    {
                      TextView,
                      layout_height="wrap_content",
                      layout_width="wrap_content",
                      text="待开发",
                      --textSize="10sp",
                      layout_gravity="center",
                    },
                  },
                },
                {
                  LinearLayout,
                  layout_height="8%h",
                  layout_width="50%w",
                  layout_weight="1.0",
                  layout_marginLeft="10dp",
                  layout_marginRight="10dp",
                  {
                    CardView;
                    layout_margin="0.5dp",
                    elevation="1.5dp";
                    id="k1";
                    layout_width="match_parent";
                    CardBackgroundColor="#00FFFFFF";
                    layout_height="match_parent";
                    radius="5dp";
                    {
                      ImageView;
                      layout_width="fill",
                      layout_height="fill",
                      id="n4";
                      onTouchListener=点击监听,
                      onClick=function()
                        弹出消息("待开发")
                      end
                    },
                    {
                      TextView,
                      layout_height="wrap_content",
                      layout_width="wrap_content",
                      text="待开发",
                      --textSize="10sp",
                      layout_gravity="center",
                    },
                  },
                },
              },
              {
                LinearLayout,
                layout_height="70dp",
                layout_width="match_parent",
                orientation="horizontal",
                {
                  LinearLayout,
                  layout_height="8%h",
                  layout_width="wrap_content",
                  layout_weight="1.0",
                  layout_margin="10dp",
                  {
                    CardView;
                    layout_margin="0.5dp",
                    elevation="1.5dp";
                    id="k1";
                    layout_width="match_parent";
                    CardBackgroundColor="#00FFFFFF";
                    layout_height="match_parent";
                    radius="5dp";
                    {
                      ImageView;
                      layout_width="fill",
                      layout_height="fill",
                      id="n5";
                      onTouchListener=点击监听,
                      onClick=function()
                        弹出消息("待开发")
                      end
                    },
                    {
                      TextView,
                      layout_height="wrap_content",
                      layout_width="wrap_content",
                      text="待开发",
                      --textSize="10sp",
                      layout_gravity="center",
                    },
                  },
                },
                {
                  LinearLayout,
                  layout_height="8%h",
                  layout_width="wrap_content",
                  layout_weight="1.0",
                  layout_margin="10dp",
                  {
                    CardView;
                    layout_margin="0.5dp",
                    elevation="1.5dp";
                    id="k1";
                    layout_width="match_parent";
                    CardBackgroundColor="#00FFFFFF";
                    layout_height="match_parent";
                    radius="5dp";
                    {
                      ImageView;
                      layout_width="fill",
                      layout_height="fill",
                      id="n6";
                      onTouchListener=点击监听,
                      onClick=function()
                        弹出消息("待开发")
                      end
                    },
                    {
                      TextView,
                      layout_height="wrap_content",
                      layout_width="wrap_content",
                      text="待开发",
                      --textSize="10sp",
                      layout_gravity="center",
                    };
                  };
                };
              };
            };
          };
        };
      };
    };
  };
  webView.addView(loadlayout(ghost))
  import "android.graphics.drawable.GradientDrawable"
  function 渐变(left_jb,right_jb,id)
    drawable = GradientDrawable(GradientDrawable.Orientation.TR_BL,{
      right_jb,
      left_jb,
    });
    id.setBackgroundDrawable(drawable)
  end
  渐变(0xff1799f9,0xff16c9ff,n1)
  渐变(0xfffdad30,0xfff2e513,n2)
  渐变(0xff6154f2,0xff6780e7,n3)
  渐变(0xff9ecece,0xff5d8cba,n4)
  渐变(0xfffc9273,0xfff7c0a1,n5)
  渐变(0xfffa8052,0xfffc9273,n6)
  f1.onClick=function()
    pg1.showPage(0)
  end
  f2.onClick=function()
    pg1.showPage(1)
  end
  f3.onClick=function()
    pg1.showPage(2)
  end
  local n=0
  function images()
    task(4000,function()
      n=n+1 pg1.showPage(n%3)
      images()
    end)
  end
  images();
  aer=true
  bt=0
  pg1.addOnPageChangeListener{
    onPageSelected=function(page)
      bt=page
    end,
    onPageScrollStateChanged=function(state)
    end,
  };